<?php
class HC_Defaults
{
    public static $defaults = array(
        'header_width'                               => '',
        'header_width_stretch'                       => true,
        'header_pos_left'                            => '',
        'header_margin_top'                          => 0,
        'header_margin_bottom'                       => 0,
        'header_margin_left'                         => 0,
        'header_margin_right'                        => 0,
        'header_font'                                => '',
        'hc_custom_css'                              => '',
        'middle_type'                                => 'default',
        'middle_bg_color'                            => '#FFFFFF',
        'middle_bg_image'                            => '',
        'middle_bg_repeat'                           => 'no-repeat',
        'middle_bg_att'                              => 'scroll',
        'middle_bg_pos'                              => 'left top',
        'middle_bg_size'                             => 'auto',
        'middle_padding'                             => 10,
        'middle_padding_lr'                          => 15,
        'middle_bo_top_color'                        => '#000000',
        'middle_bo_top_width'                        => 0,
        'middle_bo_bottom_color'                     => '#000000',
        'middle_bo_bottom_width'                     => 1,
        'middle_bo_left_color'                       => '#000000',
        'middle_bo_left_width'                       => 0,
        'middle_bo_right_color'                      => '#000000',
        'middle_bo_right_width'                      => 0,
        'middle_top-left_radius'                     => 0,
        'middle_top-right_radius'                    => 0,
        'middle_bottom-left_radius'                  => 0,
        'middle_bottom-right_radius'                 => 0,
        'mmenu_link_color'                           => '',
        'mmenu_font_size'                            => '',
        'mmenu_font_family'                          => '',
        'mmenu_link_hover_color'                     => '',
        'mmenu_link_active_color'                    => '',
        'mmenu_show_arrow'                           => true,
        'mmenu_link_bg_color'                        => '',
        'mmenu_link_hover_bg_color'                  => '',
        'mmenu_link_active_bg_color'                 => '',
        'mmenu_link_border_radius'                   => 0,
        'mmenu_item_bg_color'                        => '',
        'mmenu_item_hover_bg_color'                  => '',
        'mmenu_item_active_bg_color'                 => '',
        'mmenu_padding'                              => 20,
        'mmenu_margin'                               => 0,
        'mmenu_margin_left'                          => 0,
        'mmenu_margin_right'                         => 0,
        'mmenu_margin_lr'                            => 0,
        'mmenu_padding_lr'                           => 10,
        'mmenu_link_padding'                         => 0,
        'mmenu_link_padding_lr'                      => 0,
        'mmenu_item_border_top_color'                => '',
        'mmenu_item_border_bottom_color'             => '',
        'mmenu_item_border_left_color'               => '',
        'mmenu_item_border_right_color'              => '',
        'mmenu_item_border_top_width'                => 0,
        'mmenu_item_border_bottom_width'             => 0,
        'mmenu_item_border_left_width'               => 0,
        'mmenu_item_border_right_width'              => 0,
        'mmenu_item_border_top-left_radius'          => 0,
        'mmenu_item_border_top-right_radius'         => 0,
        'mmenu_item_border_bottom-left_radius'       => 0,
        'mmenu_item_border_bottom-right_radius'      => 0,
        'mmenu_item_border_top-left_radius_first'    => false,
        'mmenu_item_border_bottom-left_radius_first' => false,
        'mmenu_item_border_top-right_radius_last'    => false,
        'mmenu_item_border_bottom-right_radius_last' => false,
        'logo_type'                                  => 'text',
        'logo_text'                                  => '',
        'logo_max_width'                             => 200,
        'logo_src'                                   => '',
        'logo_padding'                               => 10,
        'logo_font_family'                           => '',
        'desc_font_family'                           => '',
        'show_logo_area'                             => true,
        'show_logo'                                  => true,
        'show_description'                           => true,
        'site_title_color'                           => '#000000',
        'site_title_hover_color'                     => '#999999',
        'site_title_font_size'                       => 22,
        'site_description_color'                     => '#000000',
        'site_description_font_size'                 => 16,
        'sm_depth'                                   => '0',
        'sm_is_onhover'                              => true,
        'sm_font_size'                               => '',
        'sm_link_color'                              => '',
        'sm_link_hover_color'                        => '',
        'sm_link_hover_background'                   => '',
        'sm_bg_color'                                => '',
        'sm_min_width'                               => null,
        'sm_border_top_width'                        => 0,
        'sm_border_bottom_width'                     => 0,
        'sm_border_left_width'                       => 0,
        'sm_border_right_width'                      => 0,
        'sm_border_color'                            => '#000000',
        'sm_menu_items_border_top_width'             => 1,
        'sm_menu_items_border_top_color'             => '#000000',
        'sm_menu_items_border_bottom_width'          => 0,
        'sm_menu_items_border_bottom_color'          => '#000000',
        'sm_shadow'                                  => '3px 3px 5px 1px rgba(85, 85, 85, 0.41)',
        'top_enabled'                                => false,
        'top_left_type'                              => 'menu',
        'top_right_type'                             => 'menu',
        'top_bg_color'                               => '',
        'top_bg_image'                               => '',
        'top_font_family'                            => '',
        'top_font_size'                              => '',
        'top_bg_repeat'                              => 'no-repeat',
        'top_bg_att'                                 => 'scroll',
        'top_bg_pos'                                 => 'left top',
        'top_bg_size'                                => 'auto',
        'top_bo_top_color'                           => '#000000',
        'top_bo_top_width'                           => 0,
        'top_bo_bottom_color'                        => '#000000',
        'top_bo_bottom_width'                        => 0,
        'top_bo_left_color'                          => '#000000',
        'top_bo_left_width'                          => 0,
        'top_bo_right_color'                         => '#000000',
        'top_bo_right_width'                         => 0,
        'top_top-left_radius'                        => 0,
        'top_top-right_radius'                       => 0,
        'top_bottom-left_radius'                     => 0,
        'top_bottom-right_radius'                    => 0,
        'top_padding'                                => 10,
        'top_padding_lr'                             => 15,
        'top_link_margin_lr'                         => 5,
        'top_link_padding'                           => 0,
        'top_menuitem_padding'                       => 0,
        'top_menuitem_padding_lr'                    => 0,
        'top_link_bg_color'                          => '',
        'top_link_bg_hover_color'                    => '',
        'top_link_border_color'                      => '',
        'top_link_border_width'                      => 0,
        'top_link_border_radius'                     => '',
        'top_link_color'                             => '',
        'top_text_color'                             => '',
        'top_link_hover_color'                       => '',
        'bottom_enabled'                             => false,
        'bottom_bg_color'                            => '',
        'bottom_bg_image'                            => '',
        'bottom_font_family'                         => '',
        'bottom_bg_repeat'                           => 'no-repeat',
        'bottom_bg_att'                              => 'scroll',
        'bottom_bg_pos'                              => 'left top',
        'bottom_bg_size'                             => 'auto',
        'bottom_bo_top_color'                        => '#000000',
        'bottom_bo_top_width'                        => 0,
        'bottom_bo_bottom_color'                     => '#000000',
        'bottom_bo_bottom_width'                     => 0,
        'bottom_bo_left_color'                       => '#000000',
        'bottom_bo_left_width'                       => 0,
        'bottom_bo_right_color'                      => '#000000',
        'bottom_bo_right_width'                      => 0,
        'bottom_top-left_radius'                     => 0,
        'bottom_top-right_radius'                    => 0,
        'bottom_bottom-left_radius'                  => 0,
        'bottom_bottom-right_radius'                 => 0,
        'bottom_left_type'                           => 'menu',
        'bottom_right_type'                          => 'menu',
        'bottom_padding'                             => 10,
        'bottom_padding_pages'                       => 10,
        'bottom_padding_lr'                          => 15,
        'bottom_text_color'                          => '',
        'bottom_link_color'                          => '',
        'bottom_link_hover_color'                    => '',
        'bottom_font_size'                           => '',
        'bottom_bo_top_color'                        => '#000000',
        'bottom_bo_top_width'                        => 0,
        'bottom_bo_bottom_color'                     => '#000000',
        'bottom_bo_bottom_width'                     => 0,
        'bottom_bo_left_color'                       => '#000000',
        'bottom_bo_left_width'                       => 0,
        'bottom_bo_right_color'                      => '#000000',
        'bottom_bo_right_width'                      => 0,
        'bottom_link_border_width'                   => 0,
        'bottom_menu_items_margin_lr'                => 4,
        'bcrumbs_show_home'                          => true,
        'bcrumbs_separator'                          => '&rarr;',
        'bcrumbs_separator_color'                    => '',
        'bcrumbs_separator_margin'                   => 0,
        'bcrumbs_font_size'                          => null,
        'bcrumbs_font_family'                        => '',
        'pt_color'                                   => '',
        'pt_show_on_home'                            => true,
        'pt_margin'                                  => 0,
        'pt_font_size'                               => 20,
        'pt_font_family'                             => '',
        'sb_color'                                   => '#000000',
        'sb_width'                                   => 150,
        'sb_width_exp'                               => 220,
        'sb_shadow_exp_color'                        => '',
        'sb_font_size'                               => 16,
        'sb_font_family'                             => '',
        'sb_border_width'                            => 0,
        'sb_border_color'                            => '',
        'sb_background_color'                        => '',
        'sb_padding'                                 => 0,
        'sb_padding_left'                            => 0,
        'sb_padding_right'                           => 0,
        'sb_show_icon'                               => false,
        'sb_icon_size'                               => '',
        'sb_icon_top'                                => null,
        'sb_icon_left'                               => null,
        'sb_icon_color'                              => '',
        'sb_margin_top'                              => 0,
        'sb_margin_bottom'                           => 0,
        'sb_margin_left'                             => 0,
        'sb_margin_right'                            => 0,
        'sb_top-left_radius'                         => 0,
        'sb_top-right_radius'                        => 0,
        'sb_bottom-left_radius'                      => 0,
        'sb_bottom-right_radius'                     => 0,
        'rsp_max_width'                              => 920,
        'rsp_hamburger_color'                        => '#000000',
        'sticky_enabled'                             => true,
        'sticky_offset'                              => 100,
        'sticky_top_padding'                         => 5,
        'sticky_middle_padding'                      => 5,
        'sticky_bottom_padding'                      => 5,
        'sticky_show_top'                            => false,
        'sticky_show_middle'                         => true,
        'sticky_show_bottom'                         => true,
        'menuicons_enabled'                          => false,
        'menuicons_color'                            => null,
        'menuicons_hover_color'                      => null,
        'menuicons_size'                             => null,
        'menuicons_top'                              => null,
        'menuicons_right'                            => null,
        'menuicons_withtext'                         => true
    );


    public static function get($name)
    {
        self::$defaults['sb_placeholder'] = hc_tr_string('Search') . ' &hellip;';

        if ($name == 'logo_text' && empty(self::$defaults['logo_text']))
        {
            return get_bloginfo('name');
        }

        return self::$defaults[$name];
    }


    public static function get_mods()
    {
        $result = array();
        self::$defaults['sb_placeholder'] = hc_tr_string('Search') . ' &hellip;';

        foreach (self::$defaults as $index => $val)
        {
            $result[$index] = hc_get_mod($index);
        }

        return $result;
    }
}

